### PR TITLE
Parse aliases for URLs

### PR DESCRIPTION
**Pull request by timkelty**

### CODE REVIEW

**Comment by khalwat** [comment]
What do you think about using `Craft::parseEnv()` instead (after checking the Craft version obv) and iterating through everything in the settings, not just a few select ones?

**Review by khalwat — COMMENTED** [review]
What do you think about using Craft::parseEnv() instead (after checking the Craft version obv) and iterating through everything in the settings, not just a few select ones?

The also conditional template changes to show the environment variable auto-complete UX?

**Comment by timkelty** [comment]
Yup yup. Was going to do that but was in a hurry.

**Comment by khalwat** [comment]
I think this is better handled this way -> https://github.com/nystudio107/craft-disqus/pull/15

**Pull request closed without merging**
